<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <None Include="..\..\README.md" Link="README.md" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.AI.Abstractions" Version="9.5.0" />
        <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" Version="9.5.0" />
        <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="9.5.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DatabaseGpt.Abstractions\DatabaseGpt.Abstractions.csproj" />
    </ItemGroup>

</Project>
